stages:
- build
- apply

variables:
  GROUP_NAME: "copeople"
  PROJECT_NAME: "admin-saas"
  DOMAIN_DEVELOP: 'saas.admin.copeople.dev.aks.chilunyc.com'
  DOMAIN_DEMO: 'saas.admin.copeople.demo.aks.chilunyc.com'
  IMAGE_REPOSITORY: '${GROUP_NAME}-${PROJECT_NAME}:v${CI_PIPELINE_ID}'
  FARM_TRACK_CODE: 24C4lK93

.k8s_build_image: &k8s_build_image
  stage: build
  tags:
    - builder
  cache:
    paths:
      - ./node_modules/
  script:
    - chmod +x ./ci/build/build.sh
    - ./ci/build/build.sh ${IMAGE_REPOSITORY}

.k8s_apply_deploy: &k8s_apply_deploy
  stage: apply
  tags:
    - builder
  script:
    - chmod +x ./ci/deploy/deploy.sh
    - ./ci/deploy/deploy.sh

build_image:
  <<: *k8s_build_image

apply_deploy:
  <<: *k8s_apply_deploy
  tags:
    - builder
  only:
    - develop
    - staging
